spring.application.name=Movieticketbookingwebsite
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MovieTicketBookingWebsite;encrypt=true;trustServerCertificate=true

server.port=8081

spring.datasource.username=sa
spring.datasource.password=1

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=
spring.show-sql=true
logging.level.org.springframework.security=DEBUG